### ISSUE TITLE
Should React be in `peerDependencies` instead of `optionalDependencies`

### ISSUE THREAD

**Issue by albertstill** [gilbarbara/tree-changes#15]
A [script](https://www.npmjs.com/package/only-one) I run on our server to make sure we don't have more than one version of React in node_modules just errored because this package brought in React 17 (via `react-joyride`) in addition to our React 16 version. Just checking `optionalDependencies` was meant over `peerDependencies`? It's best to let the consumer control the version of React to stop duplicate versions, I appreciate you probably want something like optional peer dependency for this repo which doesn't seem to [exist](https://github.com/npm/npm/issues/3066). A downside to `peerDependencies` will be the missing peer dep warning for non-react projects installing this lib but at least it won't cause duplicate React versions in React projects.

**Comment by gilbarbara** [comment]
This library doesn't need to install React unless you import the hook. That's why it can't be a peer dependency.

However, optional dependencies are trick as npm installs them by default. You could [skip](https://stackoverflow.com/questions/53969343/how-i-can-skip-installing-optional-dependencies-by-npm-ci) them with `--no-optional`.

I tried to find a better way, but couldn't find one but if you have a better solution, let me know.

**Comment by albertstill** [comment]
I guess one way is to make another small package e.g `tree-changes-react` that would export the hook and have the peerDependencies field, appreciate it isn't ideal to have to run two packages though.

`--no-optional` isn't always ideal because it applies to all deps it seems. Also for some people this will be a nested(indirect) dep so it won't be obvious they need to do it.

@xanido @jooj123 any ideas?

**Comment by jooj123** [comment]
React should be a peerDep because only ever want 1 version of react in deps (optionalDependencies will cause it to show up potentially twice as per the issue here) 

Consumer should be importing react manually given its a large library and ppl need time to migrate from 16 to 17

If you are importing this lib for hooks usage you are importing react anyway so install overhead is the same.

I know some non react users will get a warning about peerDeps but thats a fine compromise - better that than potentially having react twice in deps which causes various issues (runtime errors + bloated bundle etc)

Also i dont think `--no-optional` works when consumers of this lib use `yarn` ?

**Comment by albertstill** [comment]
I'm pretty sure there is only two solutions..

Make two packages, a non-react and react one. This could have advantages going forward around making changes to the hooks or tree changes api and not having to do majors for both use cases at the same time.

Or make React a peerDep. This does mean non-react consumers will get a warning on install, but the upside is their node_modules and bundle will not include a dep they don't need (if no tree shaking).

**Comment by xanido** [comment]
Could this be solved by making use of _optional_ peerDependencies via [`peerDependenciesMeta`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta)?

`peerDependenciesMeta` allows you to specify whether a peerDependency is `optional` or not. If you were to make `react` a peerDependency and mark the dependency as optional, then users installing this `tree-changes` package would not need to have React 17 installed (and it would not be installed for them).

`peerDependenciesMeta` is supported in both [npm 6.11+](https://github.com/npm/cli/releases/tag/v6.11.0) and [yarn 1.13+](https://github.com/yarnpkg/yarn/blob/a4708b29ac74df97bac45365cba4f1d62537ceb7/CHANGELOG.md#1130)

**Comment by gilbarbara** [comment]
Oops, I forgot to close this issue.

I ended up splitting the package in 0.7.0

Thanks
